# Minimal config for current EditSSC training path.

# Data
dataset: kitti
yaml_path: "/home/fbalde/EditSSC/dataset/semantic-kitti.yaml"
data_path: "/home/fbalde/scratch/datasets/semantic_kitti/dataset/sequences"
save_path: "/home/fbalde/EditSSC/models/semantic_ae"
triplane_save_path: "/home/fbalde/EditSSC/triplanes/"
num_class: 20
grid_size: [256, 256, 32]
augment_data: false
use_query_all: false
max_points: 400000
ignore_255: true
no_weights_ce: false

# Training
resume: /home/fbalde/EditSSC/models/semantic_ae/common_ae_base/75_miou=71.023.pt
bs: 4
num_workers: 0
nb_epochs: 500
lr: 0.001
lr_scheduler: true
lr_scheduler_steps: [100]
lr_scheduler_decay: 0.5
display_period: 1
eval_epoch: 1
mixed_precision: false
vq_loss_weight: 1.0

# Model (SD VQ-VAE 3D)
tri_size: [128, 128, 32]
geo_feat_channels: 4
sd_latent_channels: 8
sd_n_embed: 512
sd_vq_embed_dim: null
sd_block_out_channels: [128, 256]
sd_layers_per_block: 2
sd_norm_num_groups: 32

# for saving triplanes
data_name: "voxels"
save_name: "triplane_sem"
save_tail: ".npy"

